version: 2
updates:
- package-ecosystem: cargo
  directory: "/dhc"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  assignees:
  - jmgao
  ignore:
  - dependency-name: vergen
    versions:
    - 4.0.1
    - 4.0.2
    - 4.0.3
    - 4.1.0
    - 4.2.0
    - 5.0.0
    - 5.0.1
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.4
