language: cpp

sudo: required

services:
  - docker

before_install:
  - docker pull jmgao/debian-buster-mingw-w64
  - docker run -d -v $(pwd):/dhc jmgao/debian-buster-mingw-w64 /bin/bash -c 'while true; do sleep 1; done'

script:
  - docker exec $(docker ps -aq) /bin/bash -c 'cd /dhc/cross && ./setup.sh'
  - docker exec $(docker ps -aq) ninja -C /dhc/cross/build.$TARGET

env:
  - TARGET=32
  - TARGET=64
