version: 2
jobs:
  build-32:
    docker:
      - image: jmgao/ubuntu-cosmic-mingw-w64-rust:latest
    steps:
      - checkout
      - run:
          name: Pull submodules
          command: git submodule update --init
      - run:
          name: Generate build files
          command: ./build/generate.sh
      - run:
          name: Use older version of memchr to prevent build errors
          command: cargo update -p memchr --precise 2.3.4  
      - run:
          name: Build 32-bit
          command: ninja -C build/i686 install
      - run:
          name: Copy binaries to workspace
          command: mkdir -p /workspace/i686 && cp dist/i686/*.dll /workspace/i686
      - persist_to_workspace:
          root: /workspace
          paths:
            - i686
  build-64:
    docker:
      - image: jmgao/ubuntu-cosmic-mingw-w64-rust:latest
    steps:
      - checkout
      - run:
          name: Pull submodules
          command: git submodule update --init
      - run:
          name: Generate build files
          command: ./build/generate.sh
      - run:
          name: Use older version of memchr to prevent build errors
          command: cargo update -p memchr --precise 2.3.4  
      - run:
          name: Build 64-bit
          command: ninja -C build/x86_64 install
      - run:
          name: Copy binaries to workspace
          command: mkdir -p /workspace/x86_64 && cp dist/x86_64/*.dll /workspace/x86_64
      - persist_to_workspace:
          root: /workspace
          paths:
            - x86_64
  package:
    docker:
      - image: circleci/buildpack-deps:bionic
    steps:
      - run: mkdir /tmp/dhc
      - attach_workspace:
          at: /tmp/dhc
      - run:
          name: Create ZIP archive
          command: cd /tmp; zip -r -9 dhc.zip dhc && mv dhc.zip /tmp/dhc
      - store_artifacts:
          path: /tmp/dhc
          destination: dhc/

workflows:
  version: 2
  build:
    jobs:
      - build-32
      - build-64
      - package:
          requires:
            - build-32
            - build-64
