version: 2
jobs:
  build:
    docker:
      - image: jmgao/debian-buster-mingw-w64:20181024
    steps:
      - checkout
      - run:
          name: Generate build files
          command: ./build/generate.sh

      - run:
          name: Build 32-bit
          command: ninja -C build/i686 install
      - run:
          name: Build 64-bit
          command: ninja -C build/x86_64 install
      - store_artifacts:
          path: dist/
          destination: dhc/
